apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
---
# 2. PersistentVolumeClaim (для хранения данных)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# 3. Deployment (запуск Redis)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          # Монтируем конфиг и данные
          volumeMounts:
            - name: redis-config
              mountPath: /usr/local/etc/redis   # Куда кладем redis.conf
            - name: redis-storage
              mountPath: /data                  # Куда Redis пишет данные
          # Запускаем Redis с нашим конфигом
          command:
            - redis-server
          args:
            - /usr/local/etc/redis/redis.conf
      volumes:
        - name: redis-config
          configMap:
            name: redis-config
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis   # <--- Чтобы имя совпадало с тем, что в ConfigMap
spec:
  selector:
    app: redis
  ports:
    - port: 6379