apiVersion: v1
kind: ConfigMap
metadata:
  name: server-payments-config
  namespace: default
data:
  REDIS_PORT: "6379"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
---
# 2. Secret (СЕКРЕТНЫЕ переменные: пароли, логины, ключи)
apiVersion: v1
kind: Secret
metadata:
  name: server-payments-secret
  namespace: default
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
---
# 3. Deployment (запуск приложения)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-payments
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-payments
  template:
    metadata:
      labels:
        app: server-payments
    spec:
      containers:
        - name: server-payments
          image: anti-fraud-system-server-payments:latest
          imagePullPolicy: Never           # <-- ВАЖНО для локальной разработки
          ports:
            - containerPort: 8082  # <-- Порт внутри контейнера
              hostPort: 8082      
          env:
            # 1. Переменные из ConfigMap
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: server-payments-config
                  key: REDIS_PORT
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: server-payments-config
                  key: POSTGRES_PORT
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: server-payments-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: server-payments-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: server-payments-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: server-payments-secret
                  key: POSTGRES_PASSWORD
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8082
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: server-payments   # <--- Чтобы имя совпадало с тем, что в ConfigMap
spec:
  selector:
    app: server-payments
  ports:
    - port: 8082